export const products = [
  {
    id: 1,
    name: 'Tornillos de Alta Resistencia',
    href: '#',
    imageSrc: 'tornillos.jpg',
    imageAlt: 'Imagen de tornillos de alta resistencia.',
    price: 35000,
    color: 'Acero',
    desc: 'Tornillos diseñados para soportar altas cargas. Ideales para patinetas eléctricas y bicicletas. Envíos seguros en toda Colombia.',
    totalUnits: 50,
  },
  {
    id: 2,
    name: 'Timbres para Patinetas',
    href: '#',
    imageSrc: 'brandon-style-LjViI6K6H8g-unsplash.jpg',
    imageAlt: 'Imagen de timbres para patinetas.',
    price: 25000,
    color: 'Negro y Plata',
    desc: 'Timbres elegantes y funcionales para alertar con estilo. Compatibles con diversos modelos de patinetas. Envíos rápidos y confiables.',
    totalUnits: 35,
  },
  {
    id: 3,
    name: 'Llantas para Patinetas',
    href: '#',
    imageSrc: 'claudio-schwarz-aVMstKMYx24-unsplash.jpg',
    imageAlt: 'Imagen de llantas para patinetas.',
    price: 85000,
    color: 'Negro',
    desc: 'Llantas de alta durabilidad con excelente tracción. Perfectas para caminos urbanos y terrenos mixtos. Envíos nacionales.',
    totalUnits: 40,
  },
  {
    id: 4,
    name: 'Cargadores para Patinetas',
    href: '#',
    imageSrc: 'eric-crawford-lQE1ZDqLy10-unsplash.jpg',
    imageAlt: 'Imagen de cargadores para patinetas.',
    price: 120000,
    color: 'Negro',
    desc: 'Cargadores originales y compatibles con varios modelos de patinetas eléctricas. Máxima eficiencia energética.',
    totalUnits: 20,
  },
  {
    id: 5,
    name: 'Aceleradores para Patinetas',
    href: '#',
    imageSrc: 'josh-nuttall-zkVi57UYHIQ-unsplash.jpg',
    imageAlt: 'Imagen de aceleradores para patinetas.',
    price: 95000,
    color: 'Negro',
    desc: 'Aceleradores de respuesta rápida y diseño ergonómico. Compatibles con diferentes marcas de patinetas eléctricas.',
    totalUnits: 60,
  },
  {
    id: 6,
    name: 'Baterías para Patinetas',
    href: '#',
    imageSrc: 'kenny-eliason-209FvE_57H8-unsplash.jpg',
    imageAlt: 'Imagen de baterías para patinetas.',
    price: 150000,
    color: 'Negro',
    desc: 'Baterías de alta capacidad para patinetas eléctricas, con larga duración y rendimiento optimizado.',
    totalUnits: 25,
  },
  {
    id: 7,
    name: 'Luces LED para Patinetas',
    href: '#',
    imageSrc: 'lazar-gugleta-mGe3GRB3Swc-unsplash.jpg',
    imageAlt: 'Imagen de luces LED para patinetas.',
    price: 40000,
    color: 'Blanco y Rojo',
    desc: 'Luces LED de alta visibilidad para mejorar la seguridad al andar en patineta por la noche.',
    totalUnits: 50,
  },
  {
    id: 8,
    name: 'Manillares para Patinetas',
    href: '#',
    imageSrc: 'mike-winkler-ITDml9cVmvM-unsplash.jpg',
    imageAlt: 'Imagen de manillares para patinetas.',
    price: 60000,
    color: 'Aluminio',
    desc: 'Manillares ergonómicos y resistentes para patinetas eléctricas, fáciles de instalar y con un diseño moderno.',
    totalUnits: 30,
  },
  {
    id: 9,
    name: 'Casco de Seguridad para Patinetas',
    href: '#',
    imageSrc: 'yurii-khomitskyi-pSVllbZQgzg-unsplash.jpg',
    imageAlt: 'Imagen de casco de seguridad para patinetas.',
    price: 85000,
    color: 'Negro',
    desc: 'Casco de alta protección con certificación de seguridad, ideal para el uso en patinetas eléctricas.',
    totalUnits: 15,
  },
];
